#!/bin/bash -e

checkReboot() {
  echo Installation will take effect after reboot!!!
}

is_armbian() {
  if [ -f /boot/armbianEnv.txt ] || [ -f /boot/dietpiEnv.txt ]; then
    echo true
  else
    echo false
  fi
}

armbian_require_overlay() {
  envFile='/boot/armbianEnv.txt'
  [ -f /boot/dietpiEnv.txt ] && envFile='/boot/dietpiEnv.txt'
  overlays=$(grep '^overlays=' "$envFile" | cut -d'=' -f2)
  for arg in "$@"; do
    if grep -qE "(^|[[:space:]])$arg([[:space:]]|$)" <<< $overlays; then
      echo "Overlay ${arg} was already added to $envFile, skip..."
    else
      overlays="${overlays} ${arg}"
      echo "Added overlay: $arg"
    fi
  done
  if grep -q "^overlays=" $envFile; then
    sed -i '/^overlays=/c\'"overlays=$overlays" $envFile
  else
    echo "overlays=$overlays" >> $envFile
  fi
}

if [ "$(python3 -c 'import sys; print(f"{sys.version_info.minor >= 11}")')" = "True" ]; then
  pip3 install adafruit-circuitpython-ssd1306 --break-system-packages
else
  pip3 install adafruit-circuitpython-ssd1306
fi

systemctl enable rockpi-penta.service

model=$(tr -d '\0' </proc/device-tree/model)

case "$model" in
*"Raspberry Pi 5"*)
  raspi-config nonint do_i2c 0 >/dev/null || true
  cp /usr/bin/rockpi-penta/env/rpi5.env /etc/rockpi-penta.env
  systemctl start rockpi-penta.service
  ;;
*"Raspberry Pi 4"*)
  raspi-config nonint do_i2c 0 >/dev/null || true
  mv /usr/bin/rockpi-penta/env/rpi4.env /etc/rockpi-penta.env
  systemctl start rockpi-penta.service
  ;;
*"ROCK 5A"*)
  if [ "$(is_armbian)" = "true" ]; then
    armbian_require_overlay rk3588-i2c8-m2 rk3588-pwm14-m1
    cp /usr/bin/rockpi-penta/env/rock_5a_armbian.env /etc/rockpi-penta.env
  else
    mv /boot/dtbo/rk3588-i2c8-m2.dtbo.disabled /boot/dtbo/rk3588-i2c8-m2.dtbo || true
    mv /boot/dtbo/rk3588-pwm14-m1.dtbo.disabled /boot/dtbo/rk3588-pwm14-m1.dtbo || true
    cp /usr/bin/rockpi-penta/env/rock_5a.env /etc/rockpi-penta.env
    u-boot-update || true
  fi
  checkReboot
  ;;
*"ROCK 5C"*)
  if [ "$(is_armbian)" = "true" ]; then
    armbian_require_overlay rk3588-i2c8-m2 rk3588-pwm14-m1
    cp /usr/bin/rockpi-penta/env/rock_5c_armbian.env /etc/rockpi-penta.env
  else
    mv /boot/dtbo/rk3588-i2c8-m2.dtbo.disabled /boot/dtbo/rk3588-i2c8-m2.dtbo || true
    mv /boot/dtbo/rk3588-pwm14-m1.dtbo.disabled /boot/dtbo/rk3588-pwm14-m1.dtbo || true
    cp /usr/bin/rockpi-penta/env/rock_5c.env /etc/rockpi-penta.env
    u-boot-update || true
  fi
  checkReboot
  ;;
*"ROCK3 Model C"*)
  mv /boot/dtbo/rk3568-i2c3-m0.dtbo.disabled /boot/dtbo/rk3568-i2c3-m0.dtbo || true
  cp /usr/bin/rockpi-penta/env/rock_3c.env /etc/rockpi-penta.env
  u-boot-update || true
  checkReboot
  ;;
*"ROCK3 Model A"*)
  mv /boot/dtbo/rk3568-i2c3-m0.dtbo.disabled /boot/dtbo/rk3568-i2c3-m0.dtbo || true
  mv /boot/dtbo/rk3568-pwm15-m0.dtbo.disabled /boot/dtbo/rk3568-pwm15-m0.dtbo || true
  cp /usr/bin/rockpi-penta/env/rock_pi_3.env /etc/rockpi-penta.env
  u-boot-update || true
  checkReboot
  ;;
*"Radxa ROCK 4SE"* | *"ROCK Pi 4"*)
  if [ "$(is_armbian)" = "true" ]; then
    cp /usr/bin/rockpi-penta/overlays/rk3399-pwm1.dtbo /boot/dtb/rockchip/overlay/rockchip-rk3399-pwm1-by-rockpi-penta.dtbo
    chmod +x /boot/dtb/rockchip/overlay/rockchip-rk3399-pwm1-by-rockpi-penta.dtbo
    armbian_require_overlay rk3399-i2c7 rk3399-pwm1-by-rockpi-penta
    cp /usr/bin/rockpi-penta/env/rock_pi_4_armbian.env /etc/rockpi-penta.env
  else
    mv /boot/dtbo/rk3399-i2c7.dtbo.disabled /boot/dtbo/rk3399-i2c7.dtbo || true
    mv /boot/dtbo/rk3399-pwm1.dtbo.disabled /boot/dtbo/rk3399-pwm1.dtbo || true
    cp /usr/bin/rockpi-penta/env/rock_pi_4.env /etc/rockpi-penta.env
    u-boot-update || true
  fi
  checkReboot
  ;;
*)
  echo Not support in your board.
  exit 2
  ;;
esac
